CREATE DATABASE FifaWorldCupDb;
GO

USE FifaWorldCupDb;
GO

CREATE TABLE Members (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(30) NULL,
    CreditBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Questions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    PrizePoolType NVARCHAR(20) NOT NULL,
    QuestionText NVARCHAR(500) NOT NULL,
    IsLocked BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE MemberAnswers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    MemberId INT NOT NULL,
    QuestionId INT NOT NULL,
    AnswerText NVARCHAR(500) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);